# Runs a local development environment.
# This docker-compose.yml lives in /hack instead of /build or /deployment because:
# /build is more for actual build artifacts. Which this docker-compose does not produce
# /deployment is for deployment resources, but we're not using this to deploy anything.
# We're using this as a convenience for local development.
version: '3'
services:
  backend:
    image: golang:1.13.4
    volumes:
      - ..:/go/src/github.com/abatilo/go-gcache-redis-sample
    working_dir: /go/src/github.com/abatilo/go-gcache-redis-sample
    command: bash -c "./hack/install_tools.sh && reflex -s -- go run cmd/cached.go svc"
    ports:
      - 8000:8000
    depends_on:
      - redis-sentinel1
  redis-sentinel1:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_SET=master
      - REDIS_MASTER_HOST=redis1
    ports:
      - '26379:26379'
    depends_on:
      - redis1
  redis1:
    image: 'bitnami/redis:latest'
    volumes:
      - ./redis.conf:/bitnami/redis-sentinel/conf/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
